version: '3.8'

services:
  webapi1: &api
    hostname: webapi1
    image: brenonortega/rinha-backend-rust-q1-24:1.0.0
    environment:
      - API_PORT=8080
    networks:
      - rinha_network
    ports:
      - "8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "65MB"

  webapi2:
    <<: *api 
    hostname: webapi2

  load-balancer:
    image: nginx:1.24.0-alpine
    networks:
      - rinha_network
    ports:
      - "9999:9999"
    depends_on:
      - webapi1
      - webapi2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"

          
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_database
    networks: 
      - rinha_network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    command: [ "postgres", "-c", "config_file=/docker-entrypoint-initdb.d/postgres.conf" ]
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "200MB"

networks:
  rinha_network:
    driver: bridge