version: '3.8'

services:
  webapi1: &api
    hostname: webapi1
    build:
      context: .
      dockerfile: Dockerfile.Application
    environment:
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_TieredPGO=1
      - DOTNET_ReadyToRun=0
      - DOTNET_TC_QuickJitForLoops=1
      - NATS_DESTINATION=api02
      - NATS_OWN=api01
    networks:
      - rinha_network
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - messagequeue
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "80MB"

  webapi2:
    <<: *api 
    hostname: webapi2
    environment:
      - NATS_DESTINATION=api01
      - NATS_OWN=api02
    ports:
      - "5001:8080"

  load-balancer:
    image: nginx:1.24.0-alpine
    networks:
      - rinha_network
    ports:
      - "9999:9999"
    depends_on:
      - webapi1
      - webapi2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

  messagequeue:
    image: nats:2.7.4
    networks:
      - rinha_network
    ports:
      - "4222:4222"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_database
    networks: 
      - rinha_network
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "200MB"

networks:
  rinha_network:
    driver: bridge