version: '3.8'

services:
  webapi1: &api
    hostname: webapi1
    build:
      context: .
      dockerfile: Dockerfile.Application
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - rinha_backend
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "170MB"

  webapi2:
    <<: *api 
    hostname: webapi2
    ports:
      - "5001:8080"

  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile.LoadBalancer
    networks:
      - rinha_backend
    ports:
      - "9999:9999"
    depends_on:
      - webapi1
      - webapi2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_database
    networks: 
      - rinha_backend
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "200MB"

networks:
  rinha_backend:
    driver: bridge