version: '3.8'

services:
  webapi1: &api
    hostname: webapi1
    build:
      context: .
      dockerfile: Dockerfile.Application
    environment:
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_TieredPGO=1
      - DOTNET_ReadyToRun=0
      - DOTNET_TC_QuickJitForLoops=1
      - NATS_DESTINATION=api02
      - NATS_OWN=api01
    networks:
      - rinha_network
    ports:
      - "8080"
      - "8081"
    depends_on:
      - postgres
      - messagequeue
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "50MB"

  webapi2:
    <<: *api 
    hostname: webapi2
    environment:
      - NATS_DESTINATION=api01
      - NATS_OWN=api02
    ports:
      - "8080"
      - "8081"

  load-balancer:
    image: nginx:1.24.0-alpine
    networks:
      - rinha_network
    ports:
      - "9999:9999"
    depends_on:
      - webapi1
      - webapi2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  messagequeue:
    image: nats:2.7.4
    networks:
      - rinha_network
    ports:
      - "4222:4222"
    command: -js
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - rinha_network
    environment:
      - REDIS_PASSWORD=redis
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"
          
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_database
    networks: 
      - rinha_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    command: [ "postgres", "-c", "config_file=/docker-entrypoint-initdb.d/postgres.conf" ]
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "350MB"

networks:
  rinha_network:
    driver: bridge